### ISSUE TITLE
Error: spawn mvn ENOENT

### ISSUE THREAD

**Issue by a-zuckut** [k3po/npm-k3po#2]
When running ```node k3po-exec.js --pom /test/pom.xml --log /builds/k3po-test.log --pidFile ./builds/k3po-test.pid start``` I get the error listed below. 

Stack:
```
Error: spawn mvn ENOENT
    at exports._errnoException (util.js:1016:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

This also is making ```npm test``` fail as well.

**Comment by a-zuckut** [comment]
Fixed with https://github.com/dpwspoon/npm-k3po/pull/1
